/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Client = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Text,
  'cityStateZip' : IDL.Text,
  'fullName' : IDL.Text,
  'ssnLast4' : IDL.Text,
  'email' : IDL.Text,
  'disputeCount' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'resolvedCount' : IDL.Nat,
});
export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'investigating' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Dispute = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'clientId' : IDL.Nat,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'account' : IDL.Text,
  'bureau' : IDL.Text,
  'daysLeft' : IDL.Nat,
  'reason' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func([Client], [IDL.Nat], []),
  'addDispute' : IDL.Func([Dispute], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteDispute' : IDL.Func([IDL.Nat], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllDisputes' : IDL.Func([], [IDL.Vec(Dispute)], ['query']),
  'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
  'updateClient' : IDL.Func([Client], [], []),
  'updateDisputeStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Text,
    'cityStateZip' : IDL.Text,
    'fullName' : IDL.Text,
    'ssnLast4' : IDL.Text,
    'email' : IDL.Text,
    'disputeCount' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'resolvedCount' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'investigating' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Dispute = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'clientId' : IDL.Nat,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'account' : IDL.Text,
    'bureau' : IDL.Text,
    'daysLeft' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func([Client], [IDL.Nat], []),
    'addDispute' : IDL.Func([Dispute], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteDispute' : IDL.Func([IDL.Nat], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllDisputes' : IDL.Func([], [IDL.Vec(Dispute)], ['query']),
    'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
    'updateClient' : IDL.Func([Client], [], []),
    'updateDisputeStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };