/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'status' : string,
  'createdAt' : string,
  'cityStateZip' : string,
  'fullName' : string,
  'ssnLast4' : string,
  'email' : string,
  'disputeCount' : bigint,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'resolvedCount' : bigint,
}
export interface Dispute {
  'id' : bigint,
  'status' : Status,
  'clientId' : bigint,
  'clientName' : string,
  'date' : string,
  'account' : string,
  'bureau' : string,
  'daysLeft' : bigint,
  'reason' : string,
}
export type Status = { 'resolved' : null } |
  { 'pending' : null } |
  { 'investigating' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<[Client], bigint>,
  'addDispute' : ActorMethod<[Dispute], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteDispute' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllDisputes' : ActorMethod<[], Array<Dispute>>,
  'getApiKey' : ActorMethod<[], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApiKey' : ActorMethod<[string], undefined>,
  'updateClient' : ActorMethod<[Client], undefined>,
  'updateDisputeStatus' : ActorMethod<[bigint, Status], undefined>,
  'getVeniceModel' : ActorMethod<[], [] | [string]>,
  'setVeniceModel' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];